version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    depends_on:
      - db
  db:
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
