version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODE=staging
        - DOMAIN_PREFIX=stg
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
  db:
    ports:
      - 5432:5432
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
