// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Link is the predicate function for link builders.
type Link func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
