// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"ssib.al/ssib-al-back/ent/link"
	"ssib.al/ssib-al-back/ent/predicate"
	"ssib.al/ssib-al-back/ent/user"
)

// LinkUpdate is the builder for updating Link entities.
type LinkUpdate struct {
	config
	hooks    []Hook
	mutation *LinkMutation
}

// Where appends a list predicates to the LinkUpdate builder.
func (lu *LinkUpdate) Where(ps ...predicate.Link) *LinkUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetDomain sets the "domain" field.
func (lu *LinkUpdate) SetDomain(s string) *LinkUpdate {
	lu.mutation.SetDomain(s)
	return lu
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableDomain(s *string) *LinkUpdate {
	if s != nil {
		lu.SetDomain(*s)
	}
	return lu
}

// SetURI sets the "uri" field.
func (lu *LinkUpdate) SetURI(s string) *LinkUpdate {
	lu.mutation.SetURI(s)
	return lu
}

// SetNillableURI sets the "uri" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableURI(s *string) *LinkUpdate {
	if s != nil {
		lu.SetURI(*s)
	}
	return lu
}

// SetTargetURL sets the "target_url" field.
func (lu *LinkUpdate) SetTargetURL(s string) *LinkUpdate {
	lu.mutation.SetTargetURL(s)
	return lu
}

// SetNillableTargetURL sets the "target_url" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableTargetURL(s *string) *LinkUpdate {
	if s != nil {
		lu.SetTargetURL(*s)
	}
	return lu
}

// SetOwnerID sets the "owner_id" field.
func (lu *LinkUpdate) SetOwnerID(u uuid.UUID) *LinkUpdate {
	lu.mutation.SetOwnerID(u)
	return lu
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableOwnerID(u *uuid.UUID) *LinkUpdate {
	if u != nil {
		lu.SetOwnerID(*u)
	}
	return lu
}

// ClearOwnerID clears the value of the "owner_id" field.
func (lu *LinkUpdate) ClearOwnerID() *LinkUpdate {
	lu.mutation.ClearOwnerID()
	return lu
}

// SetOwner sets the "owner" edge to the User entity.
func (lu *LinkUpdate) SetOwner(u *User) *LinkUpdate {
	return lu.SetOwnerID(u.ID)
}

// Mutation returns the LinkMutation object of the builder.
func (lu *LinkUpdate) Mutation() *LinkMutation {
	return lu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (lu *LinkUpdate) ClearOwner() *LinkUpdate {
	lu.mutation.ClearOwner()
	return lu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LinkUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LinkUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LinkUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lu *LinkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Domain(); ok {
		_spec.SetField(link.FieldDomain, field.TypeString, value)
	}
	if value, ok := lu.mutation.URI(); ok {
		_spec.SetField(link.FieldURI, field.TypeString, value)
	}
	if value, ok := lu.mutation.TargetURL(); ok {
		_spec.SetField(link.FieldTargetURL, field.TypeString, value)
	}
	if lu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.OwnerTable,
			Columns: []string{link.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.OwnerTable,
			Columns: []string{link.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LinkUpdateOne is the builder for updating a single Link entity.
type LinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LinkMutation
}

// SetDomain sets the "domain" field.
func (luo *LinkUpdateOne) SetDomain(s string) *LinkUpdateOne {
	luo.mutation.SetDomain(s)
	return luo
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableDomain(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetDomain(*s)
	}
	return luo
}

// SetURI sets the "uri" field.
func (luo *LinkUpdateOne) SetURI(s string) *LinkUpdateOne {
	luo.mutation.SetURI(s)
	return luo
}

// SetNillableURI sets the "uri" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableURI(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetURI(*s)
	}
	return luo
}

// SetTargetURL sets the "target_url" field.
func (luo *LinkUpdateOne) SetTargetURL(s string) *LinkUpdateOne {
	luo.mutation.SetTargetURL(s)
	return luo
}

// SetNillableTargetURL sets the "target_url" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableTargetURL(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetTargetURL(*s)
	}
	return luo
}

// SetOwnerID sets the "owner_id" field.
func (luo *LinkUpdateOne) SetOwnerID(u uuid.UUID) *LinkUpdateOne {
	luo.mutation.SetOwnerID(u)
	return luo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableOwnerID(u *uuid.UUID) *LinkUpdateOne {
	if u != nil {
		luo.SetOwnerID(*u)
	}
	return luo
}

// ClearOwnerID clears the value of the "owner_id" field.
func (luo *LinkUpdateOne) ClearOwnerID() *LinkUpdateOne {
	luo.mutation.ClearOwnerID()
	return luo
}

// SetOwner sets the "owner" edge to the User entity.
func (luo *LinkUpdateOne) SetOwner(u *User) *LinkUpdateOne {
	return luo.SetOwnerID(u.ID)
}

// Mutation returns the LinkMutation object of the builder.
func (luo *LinkUpdateOne) Mutation() *LinkMutation {
	return luo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (luo *LinkUpdateOne) ClearOwner() *LinkUpdateOne {
	luo.mutation.ClearOwner()
	return luo
}

// Where appends a list predicates to the LinkUpdate builder.
func (luo *LinkUpdateOne) Where(ps ...predicate.Link) *LinkUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LinkUpdateOne) Select(field string, fields ...string) *LinkUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Link entity.
func (luo *LinkUpdateOne) Save(ctx context.Context) (*Link, error) {
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LinkUpdateOne) SaveX(ctx context.Context) *Link {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LinkUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LinkUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (luo *LinkUpdateOne) sqlSave(ctx context.Context) (_node *Link, err error) {
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Link.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, link.FieldID)
		for _, f := range fields {
			if !link.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != link.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Domain(); ok {
		_spec.SetField(link.FieldDomain, field.TypeString, value)
	}
	if value, ok := luo.mutation.URI(); ok {
		_spec.SetField(link.FieldURI, field.TypeString, value)
	}
	if value, ok := luo.mutation.TargetURL(); ok {
		_spec.SetField(link.FieldTargetURL, field.TypeString, value)
	}
	if luo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.OwnerTable,
			Columns: []string{link.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.OwnerTable,
			Columns: []string{link.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Link{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
