// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LinksColumns holds the columns for the "links" table.
	LinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "domain", Type: field.TypeString, SchemaType: map[string]string{"type": "varchar(32)"}},
		{Name: "uri", Type: field.TypeString, SchemaType: map[string]string{"type": "varchar(256)"}},
		{Name: "target_url", Type: field.TypeString, SchemaType: map[string]string{"type": "varchar(256)"}},
		{Name: "owner_id", Type: field.TypeUUID, Nullable: true},
	}
	// LinksTable holds the schema information for the "links" table.
	LinksTable = &schema.Table{
		Name:       "links",
		Columns:    LinksColumns,
		PrimaryKey: []*schema.Column{LinksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "links_users_links",
				Columns:    []*schema.Column{LinksColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "link_domain_uri",
				Unique:  true,
				Columns: []*schema.Column{LinksColumns[1], LinksColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"primary_key": "true", "type": "varchar(32)"}},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true, SchemaType: map[string]string{"type": "varchar(256)"}},
		{Name: "password_hash", Type: field.TypeString, SchemaType: map[string]string{"type": "varchar(512)"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LinksTable,
		UsersTable,
	}
)

func init() {
	LinksTable.ForeignKeys[0].RefTable = UsersTable
}
