name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Add .env file
        run: echo "DOPPLER_TOKEN=$DOPPLER_TOKEN" > .env
        env:
          DOPPLER_TOKEN: ${{secrets.DOPPLER_TOKEN}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ssib-al-test:${{github.sha}}
